name: 'Setup ElasticSearch'
description: 'Setup ElasticSearch'
author: 'getong'
branding:
  icon: 'database'
  color: 'orange'
inputs:
  elasticsearch_version:
    description: 'Version of elasticsearch to use'
    required: false
    default: 'latest'
  host_port:
    description: 'The port of host'
    required: false
    default: 9200
  container_port:
    description: 'The port of container'
    required: false
    default: 9200
  host_node_port:
    description: 'The port of host elasticsearch node_port'
    required: false
    default: 9300
  node_port:
    description: 'The port of elasticsearch node_port'
    required: false
    default: 9300
  discovery_type:
    description: 'the discovery.type envionment'
    required: false
    default: 'single-node'

runs:
  using: 'docker'
  image: 'Dockerfile'
